Don't use alpine edge repo for vips build dependencies
Newer versions of librsvg deprecate direct inclusion of librsvg-features.h. libvips has been updated to account for this (https://github.com/libvips/libvips/commit/85f7cb6ded4ac687451ebbb04f120c6c8aa5a49b) but v8.10.0 (the version used here) does not include these changes. This causes build failure when using edge repos as they contain newer versions of librsvg, for example:

	#11 1.306 svgload.c:87:10: fatal error: librsvg/librsvg-features.h: No such file or directory
	#11 1.306    87 | #include <librsvg/librsvg-features.h>
	#11 1.306       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
	#11 1.306 compilation terminated.

Signed-off-by: Ben Steadman <ben@steadbytes.com>